spring:
  application:
    name: provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.213.212:8848
        service: ${spring.application.name}
        username: nacos
        password: nacos
        namespace: public
server:
  port: 8900
